apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: test-nginx-pods-label
  template:
    metadata:
      name: test-nginx-pod
      labels: 
        app: test-nginx-pods-label
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


