apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-pod
  labels:
    app: test-nginx-pods-label
spec:
  containers:
  - name: test-nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80



